### ISSUE TITLE
Several wav files throw 'std::ios_base::failure'

### ISSUE THREAD

**Issue by Skeli789** [ipatix/wav2agb#1]
When trying to compile several Pokemon cry wav files, this error is thrown:

```
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
```

This is specifically related to the following cries found [here](https://www.pokecommunity.com/showthread.php?t=390701):
```
Aegislash
Aromatisse
Aurorus
Barbaracle
Bergmite
Braixen
Bunnelby
Clauncher
Dedenne
Diancie
Doublade
Dragalge
Floette Regular + Eternal
Froakie
Frogadier
Gogoat
Goomy
Gourgeist Small + Super
Helioptile
Heliolisk
Honedge
Inkay
Klefki
Litleo
Malamar
Noibat
Noivern
Pangoro
Pumpkaboo Small + Super
Pyroar
Slurpuff
Spewpa
Spritzee
Talonflame
Trevenant
Yveltal
Zygarde 10 + Complete
```
I have not tested any other cries yet.

**Comment by ipatix** [comment]
I cannot reproduce this. Did you make sure you're using the latest version? I did some rewrites lately and it's possibly something broke in some commits.

**Comment by ipatix** [comment]
I'm currently investigating the situation.

**Comment by ipatix** [comment]
Okay, I think I figured out the issue. It seems those WAV files have some unused trailing bytes in the end, which I forgot to implement properly.

**Comment by ipatix** [comment]
Should be fixed now. Can you try the latest commit?

**Comment by Skeli789** [comment]
Works perfectly. Thank you so much! Your tool is amazing.
