### ISSUE TITLE
No way to set loop or frequency 

### ISSUE THREAD

**Issue by Skeli789** [ipatix/wav2agb#3]
Certain tools, like [Sappy](https://www.romhacking.net/utilities/948/]), provide a function to set a default frequency and loop value when importing wav files. As far as I can tell (based on the options given), there is no option to set these values with this tool.

**Comment by ipatix** [comment]
There is no command line switch at the moment, However, you can set the loop and frequency using the SMPL chunk in the wave header.

**Comment by Skeli789** [comment]
Thank you. Are there plans to include these features? I looked into it and I saw that you are able to change the frequency and loop end point externally. However, unlike through Sappy, I don't believe there is any way to set the loop start point without Sappy.

**Comment by ipatix** [comment]
I'm currently working on a few command line parameters.

Unfortunately there is only very little software available to edit the SMPL chunk directly. I know that Wavosaur can directly edit loops and sample related information. I personally use the Polyphone Soundfont Editor to do that (but that's still a lot of work for mass editing).

**Comment by Skeli789** [comment]
Python has a decent library to modify wav files as well. I looked at what Wavosaur does, and it doesn't actually set a real loop point for the file. It simply appends data onto the end that Wavosuar uses itself (and isn't compiled for the GBA). However, I did look at some wav files after they were compiled, and it seems remarkably easy to set the loop start and frequency during compilation. The four bytes at offset 0x8 in the compiled file is the frequency, and the four bytes at offset 0xC in the compiled file is when the loop starts. This is same in compressed files, so I assume a command line option could be made to set these bytes at the end of the compilation process. I've attached a [file](https://github.com/ipatix/wav2agb/files/3263653/test.txt) with comments so you can see what I mean.

**Comment by ipatix** [comment]
Not quite sure what you're trying to tell me. Wavosaur does correctly add an SMPL chunk in the end of the file (not only the SAUR chunk). wav2agb does correctly read that information and produces a looped assembly file.

Anyway, I've pushed some new changes as 132a3cb5ed3a695d5b8087482a32aff12946a7e5
The new options can be displayed by starting wav2agb without any parameters.

**Comment by Skeli789** [comment]
Okay, thank you! Just what I was looking for.
